### ISSUE TITLE
watchOS 6 and iOS 13 Handoff Issue

### ISSUE THREAD

**Issue by de3z1e** [darjeelingsteve/uistackview_adaptivity#4]
Are you having issues with Handoff not working on watchOS 6 and iOS 13?

**Comment by darjeelingsteve** [comment]
I've just looked in to this and, yes, it appears it is no longer working on watchOS 6 and iOS 13. I've tried a few things but couldn't get it to work. I notice that you've posted on the Apple Developer forums and on StackOverflow (https://stackoverflow.com/questions/58823885/watchos-6-and-ios-13-nsuseractivity-handoff-not-working) but no-one has a working answer. Looks like this is a pretty bad bug and Apple's documentation of the new handoff mechanism on watchOS is poor. Hopefully they will fix it in a future update or update the documentation to show us where we're going wrong.

**Comment by de3z1e** [comment]
Thanks for the update and checking it on your end. I've reported the bug to Apple and will let you know if I get some resolution. Thanks again.

**Comment by de3z1e** [comment]
FYI. Latest iOS and watchOS updates fixed the handoff bug. This issue can be closed. Thanks

**Comment by darjeelingsteve** [comment]
I just saw your message and checked Handoff again and it's working for me too. Thanks for raising the issue in the first place and for notifying when Apple fixed it 👍 .
